# The version of the plugin
version: 3.0.0

# The language of the plugin messages.
language: en

# The interval in milliseconds which the camera movement recoil uses the space out rotations for a smooth effect.
# Change this value to a lower number for a smoother effect. However, this also increases the amount of traffic flow.
item-camera-movement-recoil-duration-in-ms: 20

# Value used for defining the general amount of gun damage. Edit this value if you want more or less gun damage. A
# higher number will lead to more damage, a lower number will lead to less damage.
item-gun-damage-amplifier: 1.0

# The sound guns make when pulling the trigger. This sound effect only gets played when a player attempts to shoot a
# gun with an empty magazine.
item-gun-trigger-sound: UI_BUTTON_CLICK-0.5-2-0

# Whether players start off as passive when they join training mode. Passive players cannot take damage from other
# players using the plugin's custom items. However, they can still damage one another through "normal" attacks.
training-mode-register-players-as-passive: false
